{{- if .Values.rbacEnabled }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "dagster.fullname" . }}-role
  labels:
    app: {{ template "dagster.name" . }}
    chart: {{ template "dagster.chart" .  }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"

# Allow the Dagster service account to read and write Kubernetes jobs and pods.
rules:
  - apiGroups: ["batch"]
    resources: ["jobs", "jobs/status"]
    verbs:  ["get", "list", "watch"]
  # The empty arg "" corresponds to the core API group
  - apiGroups: [""]
    resources: ["pods", "pods/log", "pods/status"]
    verbs:  ["get", "list", "watch"]
{{- end -}}